version: 2

workflows:
  multi-node:
    steps:
      -
        command: experiment.run_multi_node
        params:
          experimentType: GRPC
          workerCommand: "pip install -r requirements.txt && python mnist.py"
          workerMachineType: "p2.xlarge"
          workerContainer: tensorflow/tensorflow:1.13.1-gpu-py3
          workerCount: 2
          parameterServerCommand: "pip install -r requirements.txt && python mnist.py"
          parameterServerMachineType: "c5.xlarge"
          parameterServerContainer: tensorflow/tensorflow:1.13.1-gpu-py3
          parameterServerCount: 1
          experimentEnv: "{\"EPOCHS_EVAL\":\"5\",\"TRAIN_EPOCHS\":\"10\",\"MAX_STEPS\":\"1000\",\"EVAL_SECS\":\"10\"}"
          model:
            type: Tensorflow
          clusterId: clcjo828k
          vpc: true
