experimentType: GRPC
experimentEnv: "{\"EPOCHS_EVAL\":\"5\",\"TRAIN_EPOCHS\":\"10\",\"MAX_STEPS\":\"1000\",\"EVAL_SECS\":\"10\"}"
clusterId: clcjo828k
workerContainer: tensorflow/tensorflow:1.13.1-gpu-py3
workerMachineType: p2.xlarge
workerCommand: "pip install -r requirements.txt && python mnist.py"
workerCount: 2
workspace: https://github.com/Paperspace/mnist-sample.git
modelType: Tensorflow
vpc: true
parameterServerContainer: tensorflow/tensorflow:1.13.1-py3
parameterServerMachineType: c5.xlarge
parameterServerCommand: "python mnist.py"
parameterServerCount: 1
